### ISSUE TITLE
Extract data from proof images

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#107]
### Story

There is lots of interesting info in the proof images : 
- price tag : price, barcode
- receipt : multiple prices, no barcodes nor EAN but a "product name", date, location
- exif data : date & location ?

What if the server was able to do some image recognition, and return to the frontend all of that info ? :star_struck: 

#### Receipt

Without the product EAN or barcode, how to link to the exact product in the OFF database ? 

### Related issues

- #320
- #394
- #308

### Image examples

|Price tag|Multiple price tags|Receipt|
|---|---|---|
|![05JD3g310N](https://github.com/openfoodfacts/open-prices/assets/7147385/dad5a307-2348-48aa-88b4-05d002e089ce)|![IMG_20240127_172140](https://github.com/openfoodfacts/open-prices/assets/7147385/0a73de7b-6b74-40aa-955b-b0b286ba986d)|![receipt](https://github.com/openfoodfacts/open-prices/assets/7147385/dffcee51-9fa9-4e19-87ec-64ff759e7a06)|

**Comment by teolemon** [comment]
On this one, it's probably about building the endpoints 
- EXIF to (timestamp + lists of candidate stores)
- Image to (list of candidates barcodes + candidate prices)

Then those endpoints can be reused on proof addition, or for retro-processing

**Comment by raphodn** [comment]
On Slack you mentionned a tool/workflow you used to extract barcode info. We could use this info to list available tools ?

I've been thinking of ways to accelerate data collection, taking pictures of shelves, and having an image recognition tool that would return a list of product codes+prices.

Then would come a step to integrate the "chosen" tool in the backend ?

**Comment by teolemon** [comment]
- There are Tensorflow.JS based solutions
 - https://blog.tensorflow.org/2022/06/ocr-in-browser-using-tensorflowjs.html
 - https://demo-doctr-tensorflowjs.mindee.com/
 - Tesseract.js https://tesseract.projectnaptha.com/
- We can offload processing to Robotoff, which has all the tooling in place
- We can do it in the Open Prices backend, it's not rocket-science (possibly with the Robotoff lib)

**Comment by alexfauquette** [comment]
I gave a try few days ago with terseract, but surprisingly it has lots of false positive, and is not perfect on barcode (some digits are missing)

I need to try again with different resolution

![image](https://github.com/openfoodfacts/open-prices/assets/45398769/f28b0f56-6e2e-459f-98ab-e59c98456e7b)

**Comment by teolemon** [comment]
- We could just use Cloud Vision #320

**Comment by raphodn** [comment]
closing in favor of the 2-3 linked (and more specific) issues
