### ISSUE TITLE
Fetch non-food product data from Open Product Facts & Open Beauty Facts

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#114]
### Story

Currently we consider that a new barcode is necessarily a food product, and we fetch its data from Open Food Facts.

What if a user scans a book ? or a boardgame ? or a deodorant ?

### Solution

Sync with the OBF & OPF databases.
How to manage duplicates ? Or products that switch from one db to another ? Or are deleted ?

### Extra info

||Link|Number of products|csv size|
|---|---|---|---|
|OFF|https://world.openfoodfacts.org|3M+|855 MB|
|OBF|https://world.openbeautyfacts.org|38k|78 MB|
|OPFF|https://world.openpetfoodfacts.org|10k|22 MB|
|OPF|https://world.openproductsfacts.org|17k|39 MB|

**Comment by raphodn** [comment]
Opened an issue in the Python package to figure out how to fetch easily the dumps of the other databases

https://github.com/openfoodfacts/openfoodfacts-python/issues/220

**Comment by raphodn** [comment]
@raphael0202 is it possible to get dumps from OBF & co ?

**Comment by teolemon** [comment]
https://world.openbeautyfacts.org/data
https://world.openpetfoodfacts.org/data
https://world.openproductsfacts.org/data

They should have similar URLS, but we probably don't have fancy new stuff like JSONL

**Comment by teolemon** [comment]
https://static.openbeautyfacts.org/data/openbeautyfacts-products.jsonl.gz
https://static.openpetfoodfacts.org/data/openpetfoodfacts-products.jsonl.gz
https://static.openproductsfacts.org/data/openproductsfacts-products.jsonl.gz

**Comment by raphodn** [comment]
Ok cool ! Maybe i'll try to improve the openfoodfacts-python package first ? I'll see if I manage to get something working

**Comment by raphodn** [comment]
> 
Ok cool ! Maybe i'll try to improve the openfoodfacts-python package first ? I'll see if I manage to get something working

Here : https://github.com/openfoodfacts/openfoodfacts-python/pull/223
