### ISSUE TITLE
Clarify the product quantity unit (g or mL)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#115]
### Story

For each new product we fetch from Open Food Facts its `product_quantity`, a normalized number in g or mL.

We need to find a way to know if the product is a beverage (mL), or solid (g), so that we can display the information accordingly in the frontend (price per kg or price per L).

Linked to #77

**Comment by raphodn** [comment]
@raphael0202 @teolemon any ideas ? maybe if sync the product categories ?
and should we store the info in the backend, or manage it instead in the frontend ?

**Comment by raphael0202** [comment]
In my opinion, we should fetch `quantity` from OFF and parse it to know whether it's a beverage or not.

**Comment by raphodn** [comment]
Isn't this parsing already done in OFF server ? Might be complex to manage all the use cases (kg, g, ml, L, pounds...).

Vs using the current clean and normalised field + a way to differenciate.

But if there is no way to differenciate in the other fields then...

**Comment by raphael0202** [comment]
It's done but there is no field to indicate the unit. We can also add a new field in Product Opener (but the codebase is in Perl)

**Comment by raphodn** [comment]
Luckily a new field was recently added in Product Opener ! https://github.com/openfoodfacts/openfoodfacts-server/issues/9377
Just need to wait to be able in prod :pray:

**Comment by raphodn** [comment]
@raphael0202 actually the new fields were in last month's release : https://github.com/openfoodfacts/openfoodfacts-server/releases/tag/v2.26.0

but i don't see them appearing in the v2 API ? is there some additional code to do ?

**Comment by raphael0202** [comment]
It's available on newly updated product (ex: https://world.openfoodfacts.org/api/v2/product/0044118115928.json).
To update all products and add the field, a script should be run server-side (`update_all_products.pl`).
