### ISSUE TITLE
Endpoint to get a proofs' prices

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#160]
### Story

Given a proof_id, it is currently not easily possible to get the related prices (and it's price_count).

We could add an extra filter on the `PriceFilter`, but there is a privacy risk for private proofs.
An alternative is to create a new route `/proofs/<id>/prices` and make sure that the authenticated user is the owner of the proof

**Comment by Sudhanva-Nadiger** [comment]
Can i work on this?

**Comment by Sudhanva-Nadiger** [comment]
I dono if its correct or wrong ! thoughts came to my mind was:

we fetch proof with given id and then return the prices related to it! we alredy have prices field in proof table ! 
```py
class Proof(Base):
    id = Column(Integer, primary_key=True, index=True)

    file_path = Column(String, nullable=False)
    mimetype = Column(String, index=True)

    type = Column(ChoiceType(ProofTypeEnum))
    is_public = Column(Boolean, nullable=False, server_default="true", index=True)

    # we have prices column in this table
    prices: Mapped[list["Price"]] = relationship(back_populates="proof")
    price_count = Column(Integer, nullable=False, server_default="0", index=True)

    owner = Column(String, index=True)

    created = Column(DateTime(timezone=True), server_default=func.now(), index=True)

    __tablename__ = "proofs"
```

we can simply return that right ?

**Comment by raphodn** [comment]
Ok good !

So a new endpoint GET `/proofs/{proof_id}` that would have an additionnal field `prices` 👍

**Comment by Sudhanva-Nadiger** [comment]
> Ok good !
> 
> So a new endpoint GET `/proofs/{proof_id}` that would have an additionnal field `prices` 👍
> 
> Or would it be a new endpoint GET `/proofs/{proof_id}/prices` that would return only the prices ?
> 


can we go with `proofs/{proof_id}/prices` end point ! it gives more clarity I guess! 

> And also maybe avoid sending the proof object in each price ^^

while inserting new price in `prices` table ?

**Comment by raphodn** [comment]
> while inserting new price in prices table ?

no, what i mean is that currently in the GET /prices endpoint we return `PriceFullWithRelations` which contains the full proof object

but for our GET /proofs/{proof_id}/prices endpoint we dont need it. so maybe a `PriceFullWithRelationsWithoutProof` ?

**Comment by Sudhanva-Nadiger** [comment]
ok got it ! We will fetch the proof with given id ! then from the list of price we can delete proof attribute ! is that fine ?

**Comment by Sudhanva-Nadiger** [comment]
Also can you please review my other pull request ? 😄

**Comment by raphodn** [comment]
done in a much simpler manner in #218 :sweat_smile: 
sorry for that @Sudhanva-Nadiger :pray:
