### ISSUE TITLE
Better sync the product brands from OFF

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#165]
### Story

When we sync the products from OFF, we currently fetch the raw `brands` field.

But if we fetched instead the `brands_tags` we could have better search & filter capabilities for the Frontend.

**Comment by raphael0202** [comment]
Indeed that's the best way to do this, using the brand tag.

**Comment by raphodn** [comment]
done in #207 + additional fix in https://github.com/openfoodfacts/open-prices/commit/9402bbb7dcbcfa44c65ce45639865ec91bd2e172
