### ISSUE TITLE
Add openfoodfacts-explorer to Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/open-prices#172]
From openfoodfacts-explorer I can't query the service, as there is a cross-domain request and the open prices server does not add "openfoodfacts-explorer.vercel.app" `Access-Control-Allow-Origin`.

Example: https://openfoodfacts-explorer.vercel.app/products/3175681105423

**Comment by dq18** [comment]
Seems to have been done at commit e3e9098

**Comment by raphodn** [comment]
@VaiTon can you confirm that it still doesn't work on your side ?

**Comment by VaiTon** [comment]
@raphodn see the JS console: https://openfoodfacts-explorer.vercel.app/products/3175681105423

**Comment by raphael0202** [comment]
@VaiTon This issue is still relevant?

**Comment by VaiTon** [comment]
It doesn't seem to be :)
