### ISSUE TITLE
Add an endpoint to update a price

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices#181]
We can't update prices, which starts to become cumbersome to users.

Add a `PUT /api/v1/prices` endpoint, that allows to update all price information.
The user should only be allowed to update his/her prices.

**Comment by Sudhanva-Nadiger** [comment]
Can i work on this?

**Comment by raphodn** [comment]
Yes, go for it ! (and no need to ask :)

**Comment by Sudhanva-Nadiger** [comment]
Cool cool !👍😄

**Comment by raphodn** [comment]
Yes 1 price_id.

Might be tricky if there are changes on the product/location/proof fields 😅 (foreign key to update, and also their price_count).

Maybe just the basic fields in a v1 ?

**Comment by Sudhanva-Nadiger** [comment]
Yes ! also should we allow only price field to update or we should allow any field in `Price` model to update?

**Comment by raphodn** [comment]
I'd say all the fields that are not FK nor the owner nor auto fields like timestamps :)

price, currency, discount, date...

**Comment by Sudhanva-Nadiger** [comment]
If we change cascading on update in price schema that should do the fk updates aswell right?

**Comment by raphodn** [comment]
It would yes, but nevertheless the price_count increment / decrement mecanism would need to be completely refactored.

Better to do this in a seperate / future work.

**Comment by Sudhanva-Nadiger** [comment]
Hi @raphodn have created the pr ! please review it! if any changes needed let me know ! Thanks !

**Comment by raphodn** [comment]
fyi I made some improvements in a following PR : https://github.com/openfoodfacts/open-prices/pull/227

**Comment by raphodn** [comment]
done in #202
