### ISSUE TITLE
Translate landing page

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#184]
### Story

Currently the landing page is available in only 2 languages : 
- english : https://prices.openfoodfacts.org/
- french : https://prices.openfoodfacts.org/fr/ : https://github.com/openfoodfacts/open-prices/pull/155
- spanish : #230

### Help

See this PR - https://github.com/openfoodfacts/open-prices/pull/155 - for an example (French translation).

**Comment by raphodn** [comment]
@Apurv428

> Can we make the translation of the landing page by using libraries or Google Translate? This way, we can cover various languages that users might use.
Instead of creating separate folders, like it's done in this https://github.com/openfoodfacts/open-prices/pull/155, can we explore the above approach?

What would be your approach ? You're right that there's some duplicated code like the <head>

**Comment by Apurv428** [comment]
I'm considering using Google Translate and incorporating the languages we need, or if necessary, incorporating all the languages it offers.

**Comment by Apurv428** [comment]
@raphodn I wasn't considering a specific language. Instead, I was contemplating the incorporation of a feature that enables the translation of the website into any language the user might prefer.

**Comment by raphodn** [comment]
I see, we could leverage https://translate.openfoodfacts.org which is the crowdsourced plateform to translate Open Food Facts content. But I'm not sure how to integrate it.
Maybe move the landing page to the frontend app ? @raphael0202

**Comment by raphodn** [comment]
Frontend issue to migrate the landing page(s) there : https://github.com/openfoodfacts/open-prices-frontend/issues/364

**Comment by raphodn** [comment]
Closing as the landing page has been migrated to the Frontend 🎉
