### ISSUE TITLE
Store product scores (nutriscore, ecoscore, nova)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#237]
### Story

Currently we are missing score information in the product sync with OFF.

It would be interesting to have this in the backend, to allow re-users (and the frontend) to start showing/filtering on such info (and not just the price !)

### Implementation

data from OFF

|Field|Format|Possible values|
|---|---|---|
|`nutriscore_grade`|string|a, b, c, d, e, `unknown` `not-applicable`|
|`ecoscore_grade`|string|a, b, c, d, e, `unknown` `not-applicable`|
|`nova_group`|integer|present if not unknown|
|`nova_groups_tags`|list (always length 1)|`en:1-unprocessed-or-minimally-processed-foods`<br>`en:2-processed-culinary-ingredients`<br>`en:3-processed-foods`<br>`en:4-ultra-processed-food-and-drink-products`<br>`unknown`|

**Comment by alvarobertin** [comment]
These new fields would be for the productFull table? I understand that we need to add them to utils/OFF_FIELDS and modify tasks/import_product_db? Am I missing something else to understand?

**Comment by raphodn** [comment]
@alvarobertin yes pretty much, you can have a look at the PR that I opened for one of these fields : #239

**Comment by raphodn** [comment]
@raphael0202 regarding my question yesterday on the NOVA fields, I found an answer : if the nova group is unknown, the field `nova_group` is not returned by the API. So I was struggling to understand if/why my only option was `nova_groups_tags`. But testing with another product showed up `nova_group` integer field :)
