### ISSUE TITLE
Product stats endpoint

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#254]
### Story

In the frontend we would like to start making visualizations (graph, map). Instead of having to fetch all the data via the API, and let the frontend do the aggregation, we could instead create an endpoint `/products/{id}/stats` that would return the pre-processed data.

### Linked issues

- Open Prices frontend : https://github.com/openfoodfacts/open-prices-frontend/issues/302
- Search-a-licious : https://github.com/openfoodfacts/search-a-licious/issues/123

### Other useful links

- https://project.med3d.eu/fooddata/price_plot.html?ean=5000159451666

### Ideas

Price timeseries

**Comment by Shadows97** [comment]
I offer an automated task which every weekend calculates the average price for each product and stores it in a table. So the endpoint for the stats will only have to retrieve the data over the desired period for the product concerned.

**Comment by raphodn** [comment]
As discussed on Slack, maybe start with a simpler approach that generates the stat data per request. And see in a second iteration to calculate this data asynchronously + store it in a differant DB

**Comment by raphodn** [comment]
https://github.com/openfoodfacts/search-a-licious/issues/123 used vega-lite

**Comment by raphodn** [comment]
Opting for a generic `/prices/stats` endpoint that will aggregate price data depending on the filters provided.

Might be very time consuming to do it on thousands of prices, so maybe restrict at some point the number of prices concerned (for instance : if 1000 prices or more, than return an error message instead of doing aggregations)
