### ISSUE TITLE
Also sync products that are no longer sold ("obsolete")

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#281]
### Story

Some products that are added on Open Prices appear as "no longer sold" on Open Food Facts.
But the OFF API only returns "currently sold" products, so we don't fetch any information for the "no longer sold" / archived products.

### Example

For example : 3596710346561 : [Open Food Facts](https://world.openfoodfacts.org/product/3596710346561/sauce-tomate-poivron-aubergine-auchan) / [Open Prices](https://prices.openfoodfacts.org/app/products/3596710346561)

![image](https://github.com/openfoodfacts/open-prices/assets/7147385/a5ba2700-23a0-4af6-8b23-6d4f0406d9e1)

### Related issues

- https://github.com/openfoodfacts/openfoodfacts-python/issues/278
- https://github.com/openfoodfacts/openfoodfacts-server/issues/8338
- #114

**Comment by stephanegigandet** [comment]
@raphodn products that are marked "no longer sold" are returned by the API: https://world.openfoodfacts.org/api/v3/product/3596710346561/sauce-tomate-poivron-aubergine-auchan

**Comment by raphodn** [comment]
> @raphodn products that are marked "no longer sold" are returned by the API: https://world.openfoodfacts.org/api/v3/product/3596710346561/sauce-tomate-poivron-aubergine-auchan

After discussion on Slack, the obsolete products are indeed available in the API and in the CSV export, but not in the JSONL export. And there is no easy way to identify them.

**Comment by raphodn** [comment]
This is issue is not blocked anymore ! 
- dump is available : https://static.openfoodfacts.org/data/openfoodfacts-products_obsolete.jsonl.gz
- openfoodfacts-python was updated to support it
