### ISSUE TITLE
Store location OSM country code (e.g. FR)

### ISSUE THREAD

**Issue by monsieurtanuki** [openfoodfacts/open-prices#292]
### Problem
In "prices" locations, we have the country name (e.g. `'Italia'`), but we don't have the country code (e.g. `'IT'`).
That means that if we want to do something serious with the country data (and not just displaying the country name in some language), we need to maintain some kind of translation/code map.

### Proposed solution
In OSM they provide the country code. We could store it in "prices" location.

### Additional context
Very specific immediate use-case: displaying the country flag. It's very easy from the country code.
There are obviously more data-related use-cases, e.g. comparing prices among countries.

**Comment by raphodn** [comment]
Hi @monsieurtanuki 

good idea to store the country code, as Nominatim & Photon seem to have different 'country' formats.

for the emoji, we already use something similar in the frontend : https://github.com/openfoodfacts/open-prices-frontend/blob/master/src/data/countries-with-emoji.json

**Comment by raphodn** [comment]
OSM's list of country codes, and their related name(s) : https://wiki.openstreetmap.org/wiki/Nominatim/Country_Codes

**Comment by monsieurtanuki** [comment]
Thank you @raphodn!

Actually we already have a country referential based on [ISO 3166-1 codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2): https://github.com/openfoodfacts/openfoodfacts-dart/blob/master/lib/src/utils/country_helper.dart

Regarding the flags, we may use a map like your `.json`, but the emoji code is basically a combination of the first letter and the second letter of the country code. Cf. https://emojipedia.org/flag-italy:
> The Flag: Italy emoji is a [flag sequence](https://emojipedia.org/emoji-flag-sequence) combining [🇮 Regional Indicator Symbol Letter I](https://emojipedia.org/regional-indicator-symbol-letter-i) and [🇹 Regional Indicator Symbol Letter T](https://emojipedia.org/regional-indicator-symbol-letter-t). These display as a single emoji on supported platforms.
