### ISSUE TITLE
Store the source to know from which apps the prices are created

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#302]
### Story

- [x] new `Price.source` field
- [x] new `Proof.source` field
- [x] store the User agent ? no the `app_name` URL param (see discussion below)
- [x] Update the web app (send the `app_name` param) : https://github.com/openfoodfacts/open-prices-frontend/pull/588

### Why

To differentiate the apps that interact with the API and create the prices.

### Info

Following discussion here : https://github.com/openfoodfacts/smooth-app/issues/5195

**Comment by raphodn** [comment]
@monsieurtanuki @teolemon a few questions : 
- it's just about storing the incoming User-Agent, right ?
- in https://github.com/openfoodfacts/smooth-app/issues/5195 you mention app_name, app_version... is it multiple fields, or one string with all that info ?
- could you give an example of the current UA sent by the mobile app ?

current PR :point_down: 
```
// with Chrome
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

// with Firefox
Open Prices Web App
```

**Comment by teolemon** [comment]
I was more thinking about letting clients send arbitrary parameters as opposed to trying to be smart and getting the user agent.

**Comment by raphodn** [comment]
How is it done already ? I'd rather simply replicate your current behavior on the main app. But maybe you don't store it actually ?

**Comment by monsieurtanuki** [comment]
@raphodn This is currently the "user agent" we use in off-dart:
```dart
class UserAgent extends JsonObject {
  /// The name of your application (eg: smooth-app)
  final String name;

  /// The version of the application (1.0.0)
  final String? version;

  /// The system running the application (eg: Android+10)
  final String? system;

  /// The url of your application (eg: https://example.com)
  final String? url;

  /// Additional information about your application
  final String? comment;
// ...

```

And we use it approximately this way, adding parameters to `GET` for instance:
```dart
    map['app_name'] = OpenFoodAPIConfiguration.userAgent!.name;
    map['app_version'] = OpenFoodAPIConfiguration.userAgent!.version!;
    map['app_uuid'] = OpenFoodAPIConfiguration.uuid!;
    map['app_platform'] = OpenFoodAPIConfiguration.userAgent?.system ?? '';
    map['comment'] = OpenFoodAPIConfiguration.userAgent?.comment ?? '';
```

In short: we somehow add 5 parameters to `GET`/`POST` queries in order to know more about the caller.
* do you need all these 5 fields? I don't know.
* are these fields coming from "user agents"? Not really, we populate them with whatever is relevant.
* what could make sense, as is done with other tools, is to populate at least a single "app_name", e.g. populated with a distinct unique value like `com.mybestprices.app`.

**Comment by raphodn** [comment]
https://openfoodfacts.github.io/openfoodfacts-server/api/#authentication

![image](https://github.com/openfoodfacts/open-prices/assets/7147385/8d282663-728b-4974-ad84-810efe135662)

So the `OpenFoodAPIConfiguration` groups everything in one string afterwards ? Or it sends multiple headers.

**Comment by teolemon** [comment]
The documentation is outdated, we now have a structured way to do it.

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-server/blob/2dffe277bc2f7955ca40a315aaac553561aeb6bc/lib/ProductOpener/Products.pm#L1410

**Comment by teolemon** [comment]
I've created a doc PR: https://github.com/openfoodfacts/openfoodfacts-server/pull/10368

**Comment by raphodn** [comment]
> In short: we somehow add 5 parameters to GET/POST queries in order to know more about the caller.

Sorry to insist :sweat_smile: Can you give a concrete example of a GET & POST request ? To see if these parameters are in the url, or in the body, or in the headers...

And what other (web) apps can I inspect that pass these info to the backend ? I just check hunger games and I don't see anything for instance

**Comment by monsieurtanuki** [comment]
@raphodn I'm French and I'm an engineer, therefore I have to say: it depends.

AFAIR we can use our user agent in the header (rather for http server stat purpose), and as query parameters (for more refined stat purpose). Always in the header, and sometimes as query parameters too.

As I said in a previous message our user agent is split in 1 mandatory field (`app_name`) and 4 optional fields (`app_version`, `app_uuid`, `app_platform`, `comment`)
* We need the user agent variable to be populated
* Each populated user agent field is added to the query parameters - if the user agent is to be added to query parameters (always the case in our `GET` calls for instance)
* The user agent is _always_ added to the header, as a concatenation of all populated user agent fields (separated by a hyphen)

For instance, for our "get product by barcode" query:
* https://world.openfoodfacts.org/api/v3/product/0028400047685/
  * ?lc=en
  * &tags_lc=en
  * &app_name=off-dart+integration+tests
* header:
  * Accept: application/json
  * User-Agent:  - off-dart integration tests
  * From: grumpf

**Comment by raphodn** [comment]
Thanks @monsieurtanuki for the detailed answer.

So I'd rather not store the User Agent then (and leave it for http server stats), but look at the `app_name` URL param :+1: 

I'll implement this in the backend & web frontend !

**Comment by raphodn** [comment]
@monsieurtanuki ok it's in prod. simply passing a `?app_name=XXX` will do it.

I did the changes in the frontend app : https://github.com/openfoodfacts/open-prices-frontend/pull/588

**Comment by monsieurtanuki** [comment]
Hi @raphodn!

I've just tested in `.net` env and added the `app_name` URI parameter in both "upload proof" and "create price" methods.
OK I added the parameter.

But where am I supposed to see the `source` field in the results? Couldn't find it in "price" or "proof"...
And even then, the naming wouldn't be very wise, as we also have a `source` field in "product" where we expect values like "off" or "obf".

**Comment by raphodn** [comment]
The field is for internal stats only for now :)
To know from which sources the prices & proofs are created.

Not sure if there is any value in returning that data in the JSON responses.

You're right the naming is similar to the flavor, i'll see if I rename it or leave it as is for the time being..

**Comment by monsieurtanuki** [comment]
@raphodn I would suggest naming it `app_name` ;)

**Comment by raphodn** [comment]
Ideally i would rename `source` to `flavor` in OFF 😅
