### ISSUE TITLE
Serve https://prices.openfoodfacts.org/en/ in addition to https://prices.openfoodfacts.org/fr/ and https://prices.openfoodfacts.org/es/

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices#307]
### Problem
- I'm considering a speedy integration of the FAQ in the app, and while  https://prices.openfoodfacts.org/fr/ and https://prices.openfoodfacts.org/es/ work, https://prices.openfoodfacts.org/en/ is 404

**Comment by raphodn** [comment]
Closing in favor of #482 (move these about pages to the frontend app)
