### ISSUE TITLE
Create thumbnail of proof images

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices#340]
Following https://github.com/openfoodfacts/smooth-app/issues/5326#issuecomment-2185995548, create 400px version of all proof images.
We can use the same format as on Product Opener, `{IMAGEID}.400.{EXT}`

And also compress/convert in .webp ?

**Comment by monsieurtanuki** [comment]
@raphael0202 @raphodn ping

**Comment by raphodn** [comment]
> @raphael0202 @raphodn ping

Once #355 (Django) is deployed in prod we'll put it on the todo

**Comment by monsieurtanuki** [comment]
![image](https://github.com/user-attachments/assets/6d1998df-6c1c-4928-977d-d7e34fafa129)
