### ISSUE TITLE
Incrementing the page number on the prices endpoint seems to return duplicate prices when using location_id

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices#353]
### What
It seems like the 'Load more' button when viewing a location ID on the website is giving the same results over and over instead of returning the results for the next page. The page number is being incremented correctly, so I think this is a backend issue.
https://prices.openfoodfacts.org/app/locations/380

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Windows 10
 - Platform Desktop

### Part of
-

**Comment by raphodn** [comment]
I believe this has been fixed since :)

**Comment by odin-h** [comment]
Yes, it appears to be fixed now 😄 But I also noticed now that it's also happening with proofs too when you order by proof date:
![Image](https://github.com/user-attachments/assets/19660ac9-68cd-42c3-ba4a-144eb60793af)
I had to remove a few elements in-between to take that screenshot so they're not necessarily right next to each other, but the proof images of the cheeses both have the same proof ID.
Not sure if this issue is related or I should open a new issue?
