### ISSUE TITLE
Proof : auto classification on user upload

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#394]
### Story

Now that we are starting to have a substantial amount of proofs, we can start classifying them automatically (eg : Receipt ? Price Tag ? Product image ?) and skip having to specify the `type` on upload.

We can also run specific anaylsis depending on the inferred type (eg : if receipt, then extract number of products, amount...)

**Comment by raphael0202** [comment]
The model is now directly available as a Robotoff endpoint:
https://robotoff.openfoodfacts.org/api/v1/images/predict?models=price_proof_classification&image_url=https://prices.openfoodfacts.org/img/0010/nWVr4Wcrvm.webp

Another option is to use the model directly on the client side for optimal performance, as it's only 5.6MB. We should then implement it front-end side, with a library such as onnx web: https://onnxruntime.ai/docs/get-started/with-javascript/web.html.

**Comment by raphael0202** [comment]
All type predictions are now stored on the proof_prediction class, and returned when retrieving a single proof.
I'm closing the issue as the job is done on the backend side.
