### ISSUE TITLE
Data dump is not available anymore

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/open-prices#407]
The DB dump is not available anymore on https://prices.openfoodfacts.net/data/prices.jsonl.gz

**Comment by raphodn** [comment]
Error is `[Errno 2] No such file or directory: '/...static/data/prices.jsonl.gz'`

**Comment by raphodn** [comment]
I tested on staging, the dump command works.
The 3 jsonl.gz backup files are stored in `/static/data`

But going to the above links returns a 404. Probably an issue with nginx ?
And maybe also not the correct place to store the backup files ?

**Comment by raphael0202** [comment]
You should output the dump files in `/opt/open-prices/data` (within the container).
I've created a fake JSON file at `/opt/open-prices/data/1.json`, and it's served correctly at https://prices.openfoodfacts.net/data/1.json

**Comment by raphodn** [comment]
I did a quick test
```
docker exec -it open_prices-api-1 bash
cd static/data/
ls -ah
cp prices.jsonl.gz /opt/open-prices/data/
cp locations.jsonl.gz /opt/open-prices/data/
cp proofs.jsonl.gz /opt/open-prices/data/
```
and indeed it works :)
