### ISSUE TITLE
Rename dotenv to .env.examples

### ISSUE THREAD

**Issue by BhuwanPandey** [openfoodfacts/open-prices#443]
I think it would better to rename .env to .env.examples and untrack .env

**Comment by raphael0202** [comment]
Hello @BhuwanPandey,
Why so? We use .env in all our projects to be able to launch projects as-it and ready for development, without further configuration. If you need to tweak specific envvar, you can use a direnv file: https://direnv.net/.

**Comment by BhuwanPandey** [comment]
> Hello [@BhuwanPandey](https://github.com/BhuwanPandey), Why so? We use .env in all our projects to be able to launch projects as-it and ready for development, without further configuration. If you need to tweak specific envvar, you can use a direnv file: https://direnv.net/.

yes, we are using .env and will be using .env but i mean to say that instead of displaying .env on git publicly , i think it would be better to create .env.example which contains all variable just like .env and untrack .env .  
and
The .env.example file is just an example of the .env file. It is not used by the app.

**Comment by raphael0202** [comment]
> The .env.example file is just an example of the .env file. It is not used by the app.

The .env is used by the app when you use docker compose (which is the recommended way of launching the app): docker compose automatically load envvar from .env file.
