### ISSUE TITLE
Missing requirements.txt file in the project

### ISSUE THREAD

**Issue by scesardev** [openfoodfacts/open-prices#50]
The `requirements.txt` file mentionned in the INSTALL.md is wasn't added to the codebase.

Can you add it please ?

Thank you :)

**Comment by raphael0202** [comment]
Dependencies are now handled by poetry! The INSTALL.md needs to be updated :)

**Comment by scesardev** [comment]
As I'm not a Python developper I wasn't aware of poetry.

I'm going to have a look at it, thanks !
