### ISSUE TITLE
Price/Proof source: store mobile app version

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#502]
### Story

We currently store the `app_name` parameter as source - see #302
But we should keep track of the mobile app's version.
And Android/iOS ?

### Why

To help debug errors

**Comment by raphodn** [comment]
@monsieurtanuki would it be easy for the mobile app to also send the `?app_version` in the URL requests ?

I'm thinking this would definitely help debug stuff, for instance https://github.com/openfoodfacts/smooth-app/issues/5689 where maybe only a particular mobile version is concerned. And maybe the `app_platform` as well :) 

I would then concatenate these 3 strings into 1 and keep storing them in the `source` field

**Comment by monsieurtanuki** [comment]
@raphodn You're already supposed to have those field sent to you:
* 'app_name' (always)
* 'app_version' (if not null)
* 'app_platform' (if not null)
* 'comment' (if not null)

Would you double-check that?

**Comment by raphodn** [comment]
ok cool !

**Comment by raphodn** [comment]
In the web app we were hacking the `app_version` param to send the app page.
- in #658 we'll now store the `app_platform` and a new `app_page`
- the `app_page` will be sent by the web app thanks to https://github.com/openfoodfacts/open-prices-frontend/pull/1192
