### ISSUE TITLE
CORS error when trying to fetch the DB dumps

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#558]
### What

On a reuse project I'm trying to fetch the `locations.jsonl.gz` file from a Frontend.
But `fetch` gives me a CORS error.

Is this something that we need to configure in [nginx.conf](https://github.com/openfoodfacts/open-prices/blob/main/nginx.conf) ?
Similar to the `/img` config in that file for instance ?

### Related issues

- #195 
- #545

**Comment by raphodn** [comment]
@raphael0202 i need help 🙏

**Comment by raphael0202** [comment]
@raphodn You need to add CORS headers directive to `/data` [here](https://github.com/openfoodfacts/open-prices/blob/main/nginx.conf#L92):

```
                # Add CORS headers
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
                add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
```
