### ISSUE TITLE
New price.type field to clearly differentiate product & categories prices

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#575]
### What

Currently there are 2 types of prices : 
- ones regarding products with barcodes (with a `product_code`)
- ones regarding products without barcodes (with a `category_tag`)

But it's not clear for the API users (creating prices, or consuming data).

There is already a `Location.type` & `Proof.type` so we could mimick this for the `Price` model.

### Things to note

Prices are currently added via the web & mobile integration.
If we made this field mandatory on create, we would have an issue with current mobile users.
- we could bump the API to v2
- we could make it optional for now, and set it automatically if it is missing

**Comment by raphodn** [comment]
Todo : update the parquet schema
https://github.com/openfoodfacts/openfoodfacts-exports/blob/main/openfoodfacts_exports/exports/parquet/price.py

**Comment by raphodn** [comment]
we should also update the data.gouv description :)
https://www.data.gouv.fr/fr/datasets/open-prices/

**Comment by raphael0202** [comment]
ping @teolemon to update the dataset on data.gouv.fr (or you may give me access as well ;) )
