### ISSUE TITLE
Proofs: allow anonymous contributions

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#595]
### Story

If we want to simplify contribution and user onboarding (for instance in "community challenges"), we could allow anonymous users to upload proofs.

- owner ? set to the generic `openfoodfacts-contributors` user
  - https://world.openfoodfacts.org/contributor/openfoodfacts-contributors
- type ? restrict to only specific proofs such as PRICE_TAG & RECEIPT ? Can be implemented further down the line after we see usage (+ auto-classification in the future will avoid needing to send this field)

**Comment by teolemon** [comment]
test
