### ISSUE TITLE
Manage discounted prices

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#76]
### Story

We currently have a `price` field (mandatory, decimal) for all the items added to the database..

But for products currently discounted, we need an easy way to store the discount-related information.

I see 2 solutions : 

**1) The price field always stores the current price (full or discounted depending on the item)**
-  a boolean field `price_is_discounted` which would be False by default
- an extra decimal field `price_without_discount` which would be available to fill if the above field is True

**2) The price field always stores the full price**
- a boolean field `price_is_discounted` which would be False by default
- an extra decimal field `price_discounted` which would be available to fill if the above field is True

**Comment by raphodn** [comment]
What about the type of discount ? loyalty card, cashback, instant, 2+1 free, 50% off on the 2nd, ...

What about the source of the discount ? from the shop, from the brand, from a 3rd party coupon/app, ...

**Comment by raphodn** [comment]
@raphael0202 do you have a preference between the 2 options ?

**Comment by raphael0202** [comment]
I would rather use the paid price in the `price` field for easier comparison to non discounted products.
We can start simple by adding a field that stores the price before the discount, and add additional fields to store the type of discount (50% off the second,...)

**Comment by raphael0202** [comment]
A first version of `price_without_discount` was implemented.

**Comment by raphodn** [comment]
A second version was implemented with a new field: `discount_type`
