### ISSUE TITLE
Script to refresh Product data

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices#96]
### Story

Currently we fetch data from OpenFoodFacts when a price is added and the product is not yet in our database.
But if the product info changes on OFF, or if we add new fields to store, the existing products are not updated.

- this script could run regularly, say every week
- we'll need something similar for OpenStreetMap locations ?

**Comment by raphodn** [comment]
Linked to #103

**Comment by raphael0202** [comment]
Done :)
